config/routes.rb
PeerGrading::Application.routes.draw do

  resources :sessions, :only => [:index]
  resources :users, :only => [:index, :create]
  resources :reviews, :only => [:index, :edit, :update, :show]

  match 'login' => 'sessions#login', :as => 'login', :via => :post
  match 'logout' => 'sessions#logout', :as => 'logout'

  root :to => 'sessions#index'

end

app/models/carnegie_mellon_person.rb
class CarnegieMellonPerson < ActiveLdap::Base
  ldap_mapping :dn_attribute => "guid",
               :prefix => "ou=Person",
               :classes => ["cmuPerson"]

  def self.find_by_andrewid( andrewid )
    find("cmuandrewid=#{andrewid}", :attributes => ['cmuandrewid',
                                                    'cn', 
                                                    'mail',
                                                    'sn',
                                                    'cmuDepartment',
                                                    'cmuStudentClass'
                                                   ]) 
  end

end

app/models/review.rb
class Review < ActiveRecord::Base
  belongs_to :reviewer, :class_name => 'User'
  belongs_to :presenter, :class_name => 'User'
  attr_accessible :comments, :coolness_score, :degree_of_difficulty_score, :game, :implementation_score, :reviewer, :presenter
  
  scope :incomplete, :conditions => [ "game is NULL"]
  scope :complete, :conditions => ["game is not NULL"]

  def average
    (implementation_score + degree_of_difficulty_score + coolness_score)/3
  end

  validates :implementation_score, :numericality => { :greater_than => 0, :less_than => 11 }
  validates :degree_of_difficulty_score, :numericality => { :greater_than => 0, :less_than => 11 }
  validates :coolness_score, :numericality => { :greater_than => 0, :less_than => 11 }

end

app/models/review_group.rb
class ReviewGroup < ActiveRecord::Base
  belongs_to :owner, :class_name => 'User'
  attr_accessible :name, :owner

  has_many :users
  
end

app/models/user.rb
class User < ActiveRecord::Base
  belongs_to :review_group
  has_one :review_group_ownership, :foreign_key => :owner_id, :class_name => 'ReviewGroup'
  has_many :reviews, :foreign_key => :reviewer_id
  has_many :self_reviews, :foreign_key => :presenter_id, :class_name => 'Review'

  attr_accessible :andrewid, :username, :review_group


  def ldap_reference
    @ldap_reference ||= CarnegieMellonPerson.find_by_andrewid( self.andrewid )
    # Add new attributes to CarnegieMellonPerson attributes before adding 
    # references to them in participant.rb
  end

  def name
    Array.[](ldap_reference["cn"]).flatten.last
  end

  def surname
    ldap_reference["sn"]
  end
  
  def email
    ldap_reference["mail"]
  end

  def department
    ldap_reference["cmuDepartment"]
  end

  def student_class
    ldap_reference["cmuStudentClass"]
  end


  validates_presence_of :andrewid
  validates_presence_of :username

  validates_uniqueness_of :username, :message => "is not available. Please select an alternative."

  validate :username_is_not_andrewid, :on => :update
  
  private
  def username_is_not_andrewid
    if username == andrewid
      errors.add(:username, "Grading alias cannot be your Andrew ID.")
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_filter :require_authentication
  
  def index
    @user ||= User.find_by_username(session[:username])
    
    if @user.review_group
      @group = @user.review_group
    elsif @user.review_group_ownership
      @group = @user.review_group_ownership
    else
      render 'no_group'
    end

    unless @user.reviews.size > 0
      @group.users.each do |u|
        @user.reviews.build(:presenter => u,
                            :implementation_score => 5,
                            :degree_of_difficulty_score => 5,
                            :coolness_score => 5 )

        @user.save
      end
    end
  rescue
    flash[:error] = "Something went wrong."
    redirect_to logout_url
  end

  def edit
    @review = Review.find(params[:id])
    unless @review and @review.reviewer.username == session[:username]
      redirect_to reviews_url
    end
  rescue 
    redirect_to reviews_url
  end

  def update
    @review = Review.find(params[:id])
    unless @review and @review.reviewer.username == session[:username]
      redirect_to reviews_url
    end
    @review.update_attributes(params[:review])
    @review.save!
    redirect_to reviews_url
  rescue
    flash[:error] = "Problem saving review"
    render 'edit'
  end

  def require_authentication
    unless session[:username]
      flash[:error] = "You must be logged in."
      redirect_to sessions_url
    end
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  include SessionsHelper

  before_filter :check_if_logged_in, except: 'logout'

  def index
    @user = User.new
  end

  def login
    @user = User.find_by_username(params[:user][:username])
    
    if @user
      
      if @user.username == @user.andrewid
        flash[:error] = "You must register first."
        redirect_to sessions_url
      else
        login_user @user
        redirect_to reviews_url
      end

    else
      flash[:error] = "That grader alias is not registered."
      redirect_to sessions_url
    end
  end

  def logout
    logout_user
    flash[:notice] = "Successfully logged out."
    redirect_to root_url
  end

  private
  def check_if_logged_in
    if session[:username]
      redirect_to reviews_url
    end
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # TODO: cleanup the filter cludge

  include SessionsHelper

  before_filter :check_andrewid, :check_if_registered, :check_for_default_username, only: 'create'

  def index
    redirect_to sessions_url
  end

  def create
    @user ||= User.find_by_andrewid(params[:user][:andrewid])

    # Ok, they made it this far, let them update their grader alias
    @user.username = params[:user][:username]
    if @user.save
      login_user @user
      redirect_to reviews_url
    else
      flash[:error] = "Hold on there, skipper."
      render 'new'
    end
  end


  private
  
  # Andrew ID cannot be blank
  def check_andrewid
    if params[:user][:andrewid] == ""
      flash[:error] = "AndrewID cannot be blank"
      redirect_to sessions_url
    end
  end

  # All users are pre-created, and thus exist
  def check_if_registered
    @user ||= User.find_by_andrewid(params[:user][:andrewid])
    unless @user
      flash[:error] = "User \"" + params[:user][:andrewid] + "\" is not registered."
      redirect_to sessions_url
    end
  end

  # Only register people with unchanged usernames
  def check_for_default_username
    @user ||= User.find_by_andrewid(params[:user][:andrewid])
    unless @user.username == @user.andrewid
      flash[:error] = "This user is already registered."
      redirect_to sessions_url
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def login_user( user )
    session[:username] = user.username
  end

  def logout_user
    session[:username ] = nil
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>PeerGrading</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=350;">
</head>
<body>

<% if session[:username] %>
<nav><%= link_to "[ logout ]", logout_path %></nav>
<% end %>

<%= image_tag "gadgets.png" %>
<h1 class="wordmark">Peer Grading App</h1>

<% if flash[:error] and flash[:error] != "" %>
<div class="flash error"><%= flash[:error] %></div>
<% end %>
<% if flash[:notice] and flash[:notice] != "" %>
<div class="flash notice"><%= flash[:notice] %></div>
<% end %>


<%= yield %>

</body>
</html>

app/views/reviews/edit.html.erb
<div id="review">
<h1>Peer Grading Sheet</h1>
<h2>Presenter: <%= @review.presenter.name %></h2>
<%= form_for @review do |f| %>
<h2>Game Name:</h2><%= f.text_field :game %>

<h3>Implementation</h3>
<%= range_field :review, :implementation_score, :step => "1", :min => "1", :max => "10", :onchange => "$('#iValue').text(this.value)" %><div id="iValue"><%= @review.implementation_score %></div>

<h3>Degree of Difficulty of the project</h3>
<%= range_field :review, :degree_of_difficulty_score, :step => "1", :min => "1", :max => "10", :onchange => "$('#dValue').text(this.value)" %><div id="dValue"><%= @review.degree_of_difficulty_score %></div>
<h3>Project 'coolness' and polish</h3>
<%= range_field :review, :coolness_score, :step => "1", :min => "1", :max => "10", :onchange => "$('#cValue').text(this.value)" %><div id="cValue"><%= @review.coolness_score %></div>
<h3>Constructive Comments:</h3>
<%= f.text_area :comments, :rows => "10"  %>

<%= f.submit "Save" %>

<% end %>
</div>

app/views/reviews/index.html.erb
<div id="review_list">
<h1>Welcome, <%= @user.name %></h1>
<h2>You are a member of <%= @group.name %></h2>

<h3>Reviews ToDo</h3>
<% if @user.reviews.incomplete.size == 0 %>
<div class="none">None! :)</div>
<% else %>
<table class="epi-dataTable">
  <tr>
    <td>Name</td>
    <td>AndrewId</td>
  </tr>
<% @user.reviews.incomplete.each do |r| %>
<tr class="<%= cycle "odd", "even" %>">
  <td><%= r.presenter.name %></td>
  <td>(<%= r.presenter.andrewid %>)</td>
  <td><%= link_to "review", edit_review_url(r) %></t>
</tr>
<% end %>
</table>
<% end %>

<h3>Reviews Done</h3>
<% if @user.reviews.complete.size == 0 %>
<div class="none">None :-(</div>
<% else %>
<table class="epi-dataTable">
  <tr>
    <td>Name</td>
    <td>AndrewID</td>
    <td>Game Name</td>
    <td>Implementation</td>
    <td>Difficulty</td>
    <td>Coolness</td>
    <td>Average</td>
  </tr>
<% @user.reviews.complete.each do |r| %>
<tr class="<%= cycle "odd", "even" %>">
  <td><%= r.presenter.name %></td>
  <td>(<%= r.presenter.andrewid %>)</td>
  <td><%= r.game %></td>
  <td><%= r.implementation_score %></td>
  <td><%= r.degree_of_difficulty_score %></td>
  <td><%= r.coolness_score %></td>
  <td><%= r.average %></td>
  <td><%= link_to "edit", edit_review_url(r) %></td>
</tr>
<% end %>
</table>
<% end %>
</div>

app/views/reviews/no_group.html.erb
<h1>Welcome, <%= @user.name %></h1>
<h2>You are not enrolled in any group. Contact an instructor.</h2>

app/views/users/_register_user.html.erb
<div id="register">

  <h1>Register</h1>

  <%= form_for @user, method: :post, :url => { controller: :users, action: :create}  do |f| %>

  <label>Pick a Grading Alias/Codename:</label>
  <%= f.text_field :username %>
  <% if @user.errors.has_key? :username %>
  <span class="error"><%= @user.errors[:username].join(", ")%></span>
  <% end %>

  <label>Your Andrew ID:</label>
  <%= f.text_field :andrewid %>
  <% if @user.errors.has_key? :andrewid %>
  <span class="error"><%= raw @user.errors[:andrewid].join(", ") %></span>
  <% end %>

  <%= f.submit "Register!" %>

  <% end %>

</div>

app/views/users/new.html.erb
<%= render partial: 'register_user' %>